### PR TITLE
Enhance RocksDB backend: complete interfaces and add VersionedStore tests

### PR DESCRIPTION
**Pull request by rongma7**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)

### CODE REVIEW

**Review by ChenxingLi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)* status: 2 of 10 files reviewed, 8 unresolved discussions (waiting on @rongma7)

___
*[`Cargo.toml` line 9 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6k1O8UpZF_9jfzT0:-OET6k1O8UpZF_9jfzT1:b-s3nz64) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/Cargo.toml#L9)):*
> ```TOML
> thiserror = "1"
> auto_impl = "1.2"
> kvdb-rocksdb = { git = "https://github.com/Conflux-Chain/parity-common-rocksdb", rev = "3fcd845" }
> ```

Modify on version with `kvdb-rocksdb <= 0.19`, current branch is `0.22`.  
___
*[`src/errors.rs` line 43 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET72X65f_EoJyjHjhN:-OET72X65f_EoJyjHjhO:bi7pocy) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/errors.rs#L43)):*
> ```XML
>     Custom(&'static str),
>     #[error("An error occurred while interacting with the kvdb_rocksdb interface")]
>     RocksDbError,
> ```

Why could a db error happen on decoding?
___
*[`src/middlewares/versioned_flat_key_value/tests.rs` line 1150 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET9Csj8G2Zqbprsyvp:-OET9Csj8G2Zqbprsyvq:b-rr4y3o) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/middlewares/versioned_flat_key_value/tests.rs#L1150)):*
> ```XML
> }
> 
> fn test_versioned_store<D: DatabaseTrait>(
> ```

Use the idea of modularity to reuse code. The general parts (such as DB read/write) and the non-general parts (such as DB initialization) should be separated, rather than placed in the same function.

The current incorrect mixing leads to the need to add new functions to the `DatabaseTrait` and prevents you from properly handling the deletion of test directories.

Make the test function accept a `db: impl DatabaseTrait` parameter, and then implement the database's preprocessing and postprocessing outside the function.
___
*[`src/backends/table.rs` line 26 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6ERz2AyZWGgl_7u_:-OET6ES-Cdcz8Mg0YQpF:b306z3l) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/table.rs#L26)):*
> ```XML
> 
>     #[cfg(test)]
>     fn iter_from_start(&self) -> Result<TableIter<T>>;
> ```

Just keep this interface for non-test mode.
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET7teK8Py4V5nzDTYK:-OET7teL1X7MVQtTxZLW:b-anwe9z) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/impls/kvdb_rocksdb.rs#L22)):*
> ```XML
> }
> 
> pub fn empty_rocksdb(num_cols: u32, path: &str) -> Result<kvdb_rocksdb::Database> {
> ```

Improper name, how do you know there is no existing database on this path?

`open_database` is enough. 
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 75 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET7_iiCe0Y9m5y4Iuh:-OET7_iiCe0Y9m5y4Iui:b-spbv4c) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/impls/kvdb_rocksdb.rs#L75)):*
> ```XML
>         use crate::backends::TableName;
> 
>         let db_path = "test_database";
> ```

The temporary dir should have a prefix `__` like `__test_database`. After test, the temporary dir should be removed. 
___
*[`src/backends/mod.rs` line 27 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET5Rru5bYSD0MwPnUt:-OET5Rru5bYSD0MwPnUu:b-fo6ze3) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/mod.rs#L27)):*
> ```XML
>     /// Initializes an empty database.
>     #[cfg(test)]
>     fn empty_for_test() -> Result<Self>;
> ```

A trait should not have a conditional interface. Remove this interface from trait. 
___
*[`src/backends/table_name.rs` line 31 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6Q-dDhw-gx34jsu5:-OET6Q-dDhw-gx34jsu6:b-hg06xv) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/table_name.rs#L31)):*
> ```XML
> 
> impl TableName {
>     pub fn max_index() -> u32 {
> ```

`pub const fn`

**Review by rongma7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)* status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @ChenxingLi)

___
*[`Cargo.toml` line 9 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6k1O8UpZF_9jfzT0:-OEYbuya5XWu1Dy4nQ1s:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/Cargo.toml#L9)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Modify on version with `kvdb-rocksdb <= 0.19`, current branch is `0.22`.
</blockquote></details>

Done.
___
*[`src/errors.rs` line 43 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET72X65f_EoJyjHjhN:-OEYhRNW4ZZ1aIGYC6HI:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/errors.rs#L43)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Why could a db error happen on decoding?
</blockquote></details>

Done.
___
*[`src/backends/table.rs` line 26 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6ERz2AyZWGgl_7u_:-OETQxPM3GcihpkbA8UZ:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/table.rs#L26)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Just keep this interface for non-test mode.
</blockquote></details>

Done.
___
*[`src/backends/table_name.rs` line 31 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET6Q-dDhw-gx34jsu5:-OETR5uGCIvpZGGBHljc:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/table_name.rs#L31)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

`pub const fn`
</blockquote></details>

Done.
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 22 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET7teK8Py4V5nzDTYK:-OETRJX3CmyDnKzqNsdl:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/impls/kvdb_rocksdb.rs#L22)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Improper name, how do you know there is no existing database on this path?

`open_database` is enough.
</blockquote></details>

Done.
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 75 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET7_iiCe0Y9m5y4Iuh:-OEXvmf41A47Qs2glIpB:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/impls/kvdb_rocksdb.rs#L75)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

The temporary dir should have a prefix `__` like `__test_database`. After test, the temporary dir should be removed.
</blockquote></details>

Done.
___
*[`src/middlewares/versioned_flat_key_value/tests.rs` line 1150 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET9Csj8G2Zqbprsyvp:-OEY08y0AjA9M3PJxnMa:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/middlewares/versioned_flat_key_value/tests.rs#L1150)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Use the idea of modularity to reuse code. The general parts (such as DB read/write) and the non-general parts (such as DB initialization) should be separated, rather than placed in the same function.

The current incorrect mixing leads to the need to add new functions to the `DatabaseTrait` and prevents you from properly handling the deletion of test directories.

Make the test function accept a `db: impl DatabaseTrait` parameter, and then implement the database's preprocessing and postprocessing outside the function.
</blockquote></details>

Done.
___
*[`src/backends/mod.rs` line 27 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OET5Rru5bYSD0MwPnUt:-OEXvjPi4v846SQyGcT-:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/214dcba6c83456a252950e4b5225359ebff74ad5/src/backends/mod.rs#L27)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

A trait should not have a conditional interface. Remove this interface from trait.
</blockquote></details>

Done.

**Review by ChenxingLi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 5 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @rongma7)

___
*[`src/backends/impls/kvdb_rocksdb.rs` line 34 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OEqsUKCAMhkRFe8O8Jv:-OEqsUKCAMhkRFe8O8Jw:b-snlc37) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/7fe3b9c0ba9556692aa0e4a7eecf713faa5f8d9f/src/backends/impls/kvdb_rocksdb.rs#L34)):*
> ```XML
>         {
>             let owned = <T::Value>::decode(&v)
>                 .map_err(DatabaseError::DecodeError)?
> ```

Manually implement `From<DecodeError>`and `From<io::Error>` for `StorageError`. 

Then you can use `?` simply, instead of `map_err`.
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 48 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OEqs8EC5Qt4DSK9_xOJ:-OEqs8EC5Qt4DSK9_xOK:b-uhgvjn) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/7fe3b9c0ba9556692aa0e4a7eecf713faa5f8d9f/src/backends/impls/kvdb_rocksdb.rs#L48)):*
> ```XML
>             .map(|kv| match kv {
>                 Ok((k, v)) => Ok((
>                     Cow::Owned(<T::Key>::decode(&k)?.into_owned()),
> ```

If the input is `Vec<u8>`, use `decode_owned` instead. `SmallVec` can be converted to Vec<u8>.

Also check the other parts.

**Review by rongma7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @ChenxingLi)

___
*[`src/backends/impls/kvdb_rocksdb.rs` line 34 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OEqsUKCAMhkRFe8O8Jv:-OErSURw4VnurSdrOQzO:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/7fe3b9c0ba9556692aa0e4a7eecf713faa5f8d9f/src/backends/impls/kvdb_rocksdb.rs#L34)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Manually implement `From<DecodeError>`and `From<io::Error>` for `StorageError`. 

Then you can use `?` simply, instead of `map_err`.
</blockquote></details>

Done.
___
*[`src/backends/impls/kvdb_rocksdb.rs` line 48 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14#-OEqs8EC5Qt4DSK9_xOJ:-OErYCbc-K4Il2HbKJ8R:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/7fe3b9c0ba9556692aa0e4a7eecf713faa5f8d9f/src/backends/impls/kvdb_rocksdb.rs#L48)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

If the input is `Vec<u8>`, use `decode_owned` instead. `SmallVec` can be converted to Vec<u8>.

Also check the other parts.
</blockquote></details>

Done.

**Review by ChenxingLi — APPROVED** [review]
> Reviewed 1 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/14)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rongma7)

**Pull request merged**
