### PR TITLE
Pending Part

### PR DESCRIPTION
**Pull request by rongma7**
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1)

### CODE REVIEW

**Review by ChenxingLi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1)* status: 1 of 8 files reviewed, 20 unresolved discussions (waiting on @rongma7)

*[a discussion](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PoVMO3eM1VcVFQ7Gm:-O6PoVMO3eM1VcVFQ7Gn:b-3zilk4) (no related file):*
Fix all the cargo clippy warnings

___
___
*[`Cargo.toml` line 15 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Poi1ND0xAearJezWH:-O6Poi1ND0xAearJezWI:bi9hmlf) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/Cargo.toml#L15)):*
> ```TOML
> ethereum-types = "0.12"
> 
> in-memory-tree = { path = "src/pending_part" }
> ```

move pending part to a module in the crate
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 49 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Plf793h0eUW9yKFap:-O6Plf7ADB-I9LzUvu03:b-al44u) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/middlewares/versioned_flat_key_value/mod.rs#L49)):*
> ```XML
>                 => { Some(commit) },
>             Ok(Some(value)) => { return Ok(value) },
>             Err(e) => { return Err(StorageError::PendingError(e)) }
> ```

Adjust the orders. 
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 44 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PpYKc3aAKZL49mxRP:-O6PpYKc3aAKZL49mxRQ:b-u4r0x7) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/middlewares/versioned_flat_key_value/mod.rs#L44)):*
> ```XML
> impl<'db, T: VersionedKeyValueSchema> VersionedStore<'db, T>
> where
>     T::Key: Hash,
> ```

Add `Hash` to the `DBKey`
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 51 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PpMT29lL-7nOrURAc:-O6PpMT29lL-7nOrURAd:b5x33qx) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/middlewares/versioned_flat_key_value/mod.rs#L51)):*
> ```XML
>             Ok(None) => self.pending_part.get_parent_of_root(),
>             Err(in_memory_tree::PendingError::CommitIDNotFound(target_commit))
>                 if target_commit == commit =>
> ```

Could `target_commit != commit` happen?
___
*[`src/pending_part/src/commit_tree.rs` line 10 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Ppyx6-9jCORD3mT3R:-O6Ppyx6-9jCORD3mT3S:bwpbomm) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L10)):*
> ```XML
> type SlabIndex = usize;
> 
> pub struct TreeNode<Key: Eq + Hash + Clone, CommitId: Debug + Eq + Hash + Copy, Value: Clone> {
> ```

Don't copy `<Key: Eq + Hash + Clone, CommitId: Debug + Eq + Hash + Copy, Value: Clone>` everywhere. 
Define a trait `PendingKeyValueSchema`, with associated types `Key`, `CommitId`, `Value`.
Define a struct  `PendingKeyValueConfig<T: VersionedKeyValueSchema>`, and implement trait `PendingKeyValueSchema`. 
___
*[`src/pending_part/src/commit_tree.rs` line 45 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PrMDzCrhERX0jKS3c:-O6PrMDzCrhERX0jKS3d:b4li5go) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L45)):*
> ```XML
>     }
> 
>     fn commit_id_to_slab_index(
> ```

rename to `get_xxx_by_xxx`
___
*[`src/pending_part/src/commit_tree.rs` line 112 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PruEd4iXWHJiFgtsr:-O6PruEd4iXWHJiFgtss:b-3wj5cs) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L112)):*
> ```XML
>         let mut slab_indices = vec![subroot_slab_index];
>         let mut head = 0;
>         while head < slab_indices.len() {
> ```

Use `VecDeque`, and function`push_back`, `pop_front`
___
*[`src/pending_part/src/commit_tree.rs` line 129 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Ps8Ca48i1HJICsRx1:-O6Ps8CbAfz5CQne6goI:b-mnb1s0) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L129)):*
> ```XML
>         let mut path = Vec::new();
>         let mut set = HashSet::new();
>         while target_node.parent.is_some() {
> ```

`while let Some(xxx) {...}`
___
*[`src/pending_part/src/commit_tree.rs` line 130 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PsNgE7F5PoomcFHJJ:-O6PsNgE7F5PoomcFHJK:b-ragnzb) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L130)):*
> ```XML
>         let mut set = HashSet::new();
>         while target_node.parent.is_some() {
>             let slab_index = target_node.parent.unwrap();
> ```

`parent_slab_index`
___
*[`src/pending_part/src/commit_tree.rs` line 183 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psbd48BRNOxrCOhP-:-O6Psbd48BRNOxrCOhP0:b-8lufx1) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L183)):*
> ```XML
>         let mut target_node = self.slab_index_to_node(target_slab_index);
>         let mut commits_rev = HashMap::new();
>         loop {
> ```

`while let Some(xxx) = target_node.parent`
___
*[`src/pending_part/src/commit_tree.rs` line 205 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psl_g-aKBHIeIGa_Q:-O6Psl_g-aKBHIeIGa_R:bjyutkj) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L205)):*
> ```XML
>         PendingError<CommitId>,
>     > {
>         let current_slab_index = self.commit_id_to_slab_index(current_commit_id)?;
> ```

why not `commit_id_to_node`?
___
*[`src/pending_part/src/commit_tree.rs` line 213 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psw_pCgzQXa2-Txzp:-O6Psw_pCgzQXa2-Txzq:b8463iw) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L213)):*
> ```XML
>         while current_node.height > target_node.height {
>             current_node.current_up(&mut rollbacks);
>             current_node = self.slab_index_to_node(current_node.parent.unwrap());
> ```

consider implement a function `get_parent_node(&self, &TreeNode)->Option<&TreeNode>`
and `get_parent_node_mut(&mut self, &TreeNode)->Option<&mut TreeNode>` if needed.
___
*[`src/pending_part/src/commit_tree.rs` line 270 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PtTDgA0f-BjqeUqWJ:-O6PtTDgA0f-BjqeUqWK:b-kxoufx) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L270)):*
> ```XML
>     }
> 
>     pub fn current_up(&self, rollbacks: &mut HashMap<Key, Option<CommitId>>) {
> ```

confusing function name, rename it.
___
*[`src/pending_part/src/commit_tree.rs` line 276 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PtXY6BlY1BjyhaEVe:-O6PtXY6BlY1BjyhaEVf:b-kxoufx) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L276)):*
> ```XML
>     }
> 
>     pub fn target_up(&self, commits_rev: &mut HashMap<Key, (CommitId, Option<Value>)>) {
> ```

confusing function name, rename it.
___
*[`src/pending_part/src/error.rs` line 5 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlP5q6L5xNGt6bpeJ:-O6PlP5q6L5xNGt6bpeK:bkke0ea) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/error.rs#L5)):*
> ```XML
> use thiserror::Error;
> 
> #[derive(Debug, PartialEq, Error)]
> ```

And `Eq`
___
*[`src/pending_part/src/versioned_hash_map.rs` line 54 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PkeYn32pEvSzx68Vx:-O6PkeYn32pEvSzx68Vy:b-1n86uq) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L54)):*
> ```XML
>             let history_inner_map = self.history
>                 .entry(commit_id)
>                 .or_insert_with(HashMap::new);
> ```

Move `history_inner_map` outside the loop.
___
*[`src/pending_part/src/versioned_hash_map.rs` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Pkpmj43NoHpLx7EEb:-O6Pkpmj43NoHpLx7EEc:b-nc36x3) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L56)):*
> ```XML
>                 .or_insert_with(HashMap::new);
>             history_inner_map.insert(key.clone(), value.clone());
>             let old_commit_id = {
> ```

unnecessary bracket
___
*[`src/pending_part/src/versioned_hash_map.rs` line 107 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlUof21plX81zgWKV:-O6PlUof21plX81zgWKW:blt7plt) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L107)):*
> ```XML
>             self.current_node = None;
>         } else {
>             self.walk_to_node_unchecked(target_commit_id.unwrap())?;
> ```

use `if let Some(xxx) = self.current_node { xxx } else {...}`, instead of `unwrap`
___
*[`src/pending_part/src/versioned_hash_map.rs` line 120 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlCQQ4WWYO06pPQ5R:-O6PlCQQ4WWYO06pPQ5S:blt7plt) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L120)):*
> ```XML
>         } else {
>             self.tree
>                 .lca(self.current_node.unwrap(), target_commit_id)?
> ```

use `if let Some(xxx) = self.current_node { xxx } else {...}`, instead of `unwrap`

**Review by rongma7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1)* status: 0 of 11 files reviewed, 20 unresolved discussions (waiting on @ChenxingLi)

*[a discussion](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PoVMO3eM1VcVFQ7Gm:-O6VA5vX9GPsYQtXiQUT:b-896fix) (no related file):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Fix all the cargo clippy warnings
</blockquote></details>

Done.

___
___
*[`Cargo.toml` line 15 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Poi1ND0xAearJezWH:-O6Pylc_72dplGzufAsc:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/Cargo.toml#L15)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

move pending part to a module in the crate
</blockquote></details>

Done.
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 49 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Plf793h0eUW9yKFap:-O6Q1j3SAzKgxXhQTM16:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/middlewares/versioned_flat_key_value/mod.rs#L49)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Adjust the orders.
</blockquote></details>

Done.
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 44 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PpYKc3aAKZL49mxRP:-O6Pze3q64bOc-krqYf1:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/middlewares/versioned_flat_key_value/mod.rs#L44)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Add `Hash` to the `DBKey`
</blockquote></details>

Done.
___
*[`src/middlewares/versioned_flat_key_value/mod.rs` line 51 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PpMT29lL-7nOrURAc:-O6Q0vWM7KxTfNkTQbBh:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/middlewares/versioned_flat_key_value/mod.rs#L51)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Could `target_commit != commit` happen?
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 10 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Ppyx6-9jCORD3mT3R:-O6QY1om7ugTKDPc46dW:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L10)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Don't copy `<Key: Eq + Hash + Clone, CommitId: Debug + Eq + Hash + Copy, Value: Clone>` everywhere. 
Define a trait `PendingKeyValueSchema`, with associated types `Key`, `CommitId`, `Value`.
Define a struct  `PendingKeyValueConfig<T: VersionedKeyValueSchema>`, and implement trait `PendingKeyValueSchema`.
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 45 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PrMDzCrhERX0jKS3c:-O6QYVN74QGfMfpuCpSg:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L45)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

rename to `get_xxx_by_xxx`
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 112 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PruEd4iXWHJiFgtsr:-O6Ttq-fCCHuOAp5h-1V:b-dyk7is) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L112)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Use `VecDeque`, and function`push_back`, `pop_front`
</blockquote></details>

We need to return `slab_indices`, but using a Deque would involve removing elements from the front and then adding them into another Vec. This approach would be less efficient for our purposes.
___
*[`src/pending_part/src/commit_tree.rs` line 129 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Ps8Ca48i1HJICsRx1:-O6Tx4q7CH2T9kaH0uZM:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L129)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

`while let Some(xxx) {...}`
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 130 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PsNgE7F5PoomcFHJJ:-O6Tx5fH8aB3n_ZGFcxb:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L130)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

`parent_slab_index`
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 183 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psbd48BRNOxrCOhP-:-O6Tygpc8evPoy6pY4sP:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L183)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

`while let Some(xxx) = target_node.parent`
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 205 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psl_g-aKBHIeIGa_Q:-O6U-OnG-34vPr40QJ9z:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L205)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

why not `commit_id_to_node`?
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 213 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Psw_pCgzQXa2-Txzp:-O6Uxmj42uMUFXlxYSFD:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L213)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

consider implement a function `get_parent_node(&self, &TreeNode)->Option<&TreeNode>`
and `get_parent_node_mut(&mut self, &TreeNode)->Option<&mut TreeNode>` if needed.
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 270 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PtTDgA0f-BjqeUqWJ:-O6U3tCk1MDh1gCoTYGH:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L270)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

confusing function name, rename it.
</blockquote></details>

Done.
___
*[`src/pending_part/src/commit_tree.rs` line 276 at r2](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PtXY6BlY1BjyhaEVe:-O6U3tYB-f_W3jFHBHyN:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/0b4ea80fabb91b2cbe22a98eb024307fa5ac06a8/src/pending_part/src/commit_tree.rs#L276)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

confusing function name, rename it.
</blockquote></details>

Done.
___
*[`src/pending_part/src/error.rs` line 5 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlP5q6L5xNGt6bpeJ:-O6U4kqi8Te9xjsPdFuk:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/error.rs#L5)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

And `Eq`
</blockquote></details>

Done.
___
*[`src/pending_part/src/versioned_hash_map.rs` line 54 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PkeYn32pEvSzx68Vx:-O6U946i3Rpd1QcaPfwY:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L54)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Move `history_inner_map` outside the loop.
</blockquote></details>

Done.
___
*[`src/pending_part/src/versioned_hash_map.rs` line 56 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Pkpmj43NoHpLx7EEb:-O6UFwvH3-v4bXiIP94A:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L56)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

unnecessary bracket
</blockquote></details>

Done.
___
*[`src/pending_part/src/versioned_hash_map.rs` line 107 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlUof21plX81zgWKV:-O6Uu5O00SNnZPjroTTj:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L107)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

use `if let Some(xxx) = self.current_node { xxx } else {...}`, instead of `unwrap`
</blockquote></details>

Done.
___
*[`src/pending_part/src/versioned_hash_map.rs` line 120 at r1](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6PlCQQ4WWYO06pPQ5R:-O6Uu2nVDp2EV6SxPaw1:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/e56791b139b97339dbde11cbb5484995fd1f66fb/src/pending_part/src/versioned_hash_map.rs#L120)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

use `if let Some(xxx) = self.current_node { xxx } else {...}`, instead of `unwrap`
</blockquote></details>

Done.

**Review by ChenxingLi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r3, 1 of 3 files at r4, 4 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @rongma7)

___
*[`src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs` line 16 at r6](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Z7XTUCsmFlA8cGzwl:-O6Z7XTUCsmFlA8cGzwm:b-b3r9vf) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/61fbf5a873221b0c9c7091efc0c6c20649208e79/src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs#L16)):*
> ```XML
> }
> 
> pub type Modifications<S> = Vec<(
> ```

Define

```
type Key<S> = <S as PendingKeyValueSchema>::Key;
type Value<S> = <S as PendingKeyValueSchema>::Value;
type CommitId<S> = <S as PendingKeyValueSchema>::CommitId;
```
and rewrite to
`pub type Modifications<S> = Vec<(Key<S>, Option<Value<S>>, Option<CommitId<S>>)>;`
___
*[`src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs` line 28 at r6](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Z7mJx9hJV2DuLM3LL:-O6Z7mJx9hJV2DuLM3LM:bf8weap) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/61fbf5a873221b0c9c7091efc0c6c20649208e79/src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs#L28)):*
> ```XML
>     ),
> >;
> pub type Rollbacks<S> =
> ```

For types that appear 3 times or fewer, a type alias is not necessary.

In a context with `S: PendingKeyValueSchema`, `HashMap<S::Key, Option<S::CommitId>>` is enough.

**Review by rongma7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @ChenxingLi)

___
*[`src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs` line 16 at r6](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Z7XTUCsmFlA8cGzwl:-O6ZFbCf5veXhoG05oyl:b-896fix) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/61fbf5a873221b0c9c7091efc0c6c20649208e79/src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs#L16)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

Define

```
type Key<S> = <S as PendingKeyValueSchema>::Key;
type Value<S> = <S as PendingKeyValueSchema>::Value;
type CommitId<S> = <S as PendingKeyValueSchema>::CommitId;
```
and rewrite to
`pub type Modifications<S> = Vec<(Key<S>, Option<Value<S>>, Option<CommitId<S>>)>;`
</blockquote></details>

Done.
___
*[`src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs` line 28 at r6](https://reviewable.io/reviews/Conflux-Chain/cfx-storage2/1#-O6Z7mJx9hJV2DuLM3LL:-O6ZQlSJ53y2hTn10pF2:b4sk3ec) ([raw file](https://github.com/Conflux-Chain/cfx-storage2/blob/61fbf5a873221b0c9c7091efc0c6c20649208e79/src/middlewares/versioned_flat_key_value/pending_part/pending_schema.rs#L28)):*
<details><summary><i>Previously, ChenxingLi (Chenxing Li) wrote…</i></summary><blockquote>

For types that appear 3 times or fewer, a type alias is not necessary.

In a context with `S: PendingKeyValueSchema`, `HashMap<S::Key, Option<S::CommitId>>` is enough.
</blockquote></details>

CIdVec, ToCommit, and RollComm are to deal with #[warn(clippy::type_complexity)].

**Pull request closed without merging**
